include ../Make.rules

SRCOBJS	=\
	Tri2dFCManager.o		\
	initialize.o			\
	finalize.o			\
	plot.o				\
	tri2dFCManInputRead.o		\
	initSolver.o			\
	output.o			\
	takePseudoStep.o		\
	mgMap.o				\
	convHistory.o			\
	restrict.o			\
	prolong.o


all:	$(SRCOBJS)

clean:
	$(RM) *.o *~

