MODULE Pre

	INTEGER,PARAMETER:: sp = SELECTED_REAL_KIND(4)
	INTEGER,PARAMETER:: dp = SELECTED_REAL_KIND(8)
	INTEGER,PARAMETER:: qp = SELECTED_REAL_KIND(16)
	
	INTEGER,PARAMETER:: wp = dp
contains

END MODULE Pre
