///\cond extern
extern "C" void strand2dfcinputread_(const int&,
				     const char*,
				     const int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int&,
				     int*,
				     int*,
				     int&,
				     int&,
				     int&,
				     int&,
				     double&,
				     double&,
				     double&,
				     double&,
				     double&,
				     double&,
				     char*);
///\endcond
